name: ksuid
version: 1.0.0
description: KSUID Generator and Parser for Dart
homepage: https://github.com/Fluttering-Health/ksuid
repository: https://github.com/Fluttering-Health/ksuid
issue_tracker: https://github.com/Fluttering-Health/ksuid/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
